[package]
name = "My_first_rougelike"
version = "1.61.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = {version = "0.8.0"}
specs = "0.16.1"
specs-derive = "0.4.1"